name: Code Analysis

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        actions:
          - name: 'Composer Validate'
            run: composer validate

          - name: 'PHPStan'
            run: composer phpstan

          - name: 'ECS'
            run: composer cs:check

          - name: 'Rector'
            run: composer rector:check

    name: ${{ matrix.actions.name }}

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: "ramsey/composer-install@v1"

      - run: ${{ matrix.actions.run }}
