name: Code Analysis

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'

jobs:
  code_analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
        actions:
          - name: 'Composer Validate'
            run: composer validate

          - name: 'PHPArkitect'
            run: composer arkitect

          - name: 'PHPStan'
            run: composer phpstan

          - name: 'ECS'
            run: composer cs:check

          - name: 'Rector'
            run: composer rector:check

    name: "${{ matrix.actions.name }} @ PHP${{ matrix.php-version }}"

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: ramsey/composer-install@v2

      - run: "${{ matrix.actions.run }}"
