name: Tests

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  tests:
    name: "Tests @ PHP${{ matrix.php-version }} ${{ matrix.composer-flags }}"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        composer-flags: [ "" ]
        include:
          - php-version: 7.4
            composer-flags: "--prefer-lowest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: bcmath,intl,mbstring
          ini-values: memory_limit=640M

      - name: "Install dependencies"
        run: composer update --no-interaction --no-progress --no-scripts ${{ matrix.composer-flags }}

      - name: "Tests"
        run: composer phpunit -- --colors=always
