name: Tests

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  tests:
    name: "Tests @ PHP${{ matrix.php-version }}"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
        script:
          - "composer phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: bcmath,intl,mbstring
          ini-values: memory_limit=640M

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Tests"
        run: "${{ matrix.script }}"
